apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: CLERK_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: CLERK_SECRET_KEY
                  name: env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env
            - name: DOMAIN_URL
              valueFrom:
                configMapKeyRef:
                  key: DOMAIN_URL
                  name: env
            - name: MERCHANT_ID
              valueFrom:
                configMapKeyRef:
                  key: MERCHANT_ID
                  name: env
            - name: MERCHANT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: MERCHANT_SECRET
                  name: env
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
                  name: env
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
                  name: env
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
                  name: env
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
                  name: env
            - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
                  name: env
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
              valueFrom:
                configMapKeyRef:
                  key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
                  name: env
            - name: NODE_ENV
              value: production
            - name: NOTIFY_URL
              valueFrom:
                configMapKeyRef:
                  key: NOTIFY_URL
                  name: env
            - name: PUSHER_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_ID
                  name: env
            - name: PUSHER_APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_APP_KEY
                  name: env
            - name: PUSHER_CLUSTER
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_CLUSTER
                  name: env
            - name: PUSHER_SECRET
              valueFrom:
                configMapKeyRef:
                  key: PUSHER_SECRET
                  name: env
            - name: REACT_APP_GEMINI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: REACT_APP_GEMINI_API_KEY
                  name: env
          image: web
          name: web
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
